name: MonoGS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=12.1
  - plyfile=0.8.1
  - python=3.10
  - pip=22.3.1
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
