inherit_from: "configs/rgbd/livo/base_config.yaml"

Dataset:
  # dataset_path: "datasets/livo/hku1/"
  # dataset_path: "datasets/livo/Visual_Challenge/"
  dataset_path: "datasets/livo/LiDAR_Degenerate/"
  Calibration:
    fx: 431.71205
    fy: 431.70855
    cx: 310.833037316
    cy: 266.985989326
    k1: 0.
    k2: 0.
    p1: 0.
    p2: 0.
    k3: 0.
    width: 640
    height: 512
    depth_scale: 256
    distorted: False